import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#fafafa",
    padding: 16,
    fontFamily: "system-ui, sans-serif",
  },
  card: { background: "#fff", borderRadius: 12, padding: 18, boxShadow: "0 2px 12px rgba(0,0,0,.08)" },
  grid: { display: "grid", gridTemplateColumns: "360px 1fr", gap: 16, marginTop: 12 },
  left: { borderRight: "1px solid #eee", paddingRight: 16 },
  right: {},
  h3: { fontSize: 14, margin: "8px 0" },
  subtle: { fontSize: 12, color: "#666" },
  error: { color: "#c00", fontSize: 13 },
  button: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "none",
    background: "linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888)",
    color: "#fff",
    fontWeight: 600,
    cursor: "pointer",
  },
  buttonSec: {
    marginTop: 12,
    width: "100%",
    padding: 10,
    borderRadius: 10,
    border: "1px solid #ddd",
    background: "#fff",
    cursor: "pointer",
  },
  pre: { fontSize: 11, background: "#f7f7f9", padding: 10, borderRadius: 8, overflow: "auto" },
  pageRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    padding: 8,
    border: "1px solid #eee",
    borderRadius: 8,
    marginBottom: 8,
  },
  pageName: { fontWeight: 600, fontSize: 13 },
  smallBtn: {
    padding: "6px 10px",
    borderRadius: 8,
    border: "none",
    background: "#E1306C",
    color: "#fff",
    cursor: "pointer",
    fontSize: 12,
  },
  smallBtnSec: {
    padding: "6px 10px",
    borderRadius: 8,
    border: "1px solid #ddd",
    background: "#fff",
    cursor: "pointer",
    fontSize: 12,
  },
  select: { width: "100%", height: 36, marginBottom: 12, borderRadius: 8, border: "1px solid #ddd" },
  chatGrid: { display: "grid", gridTemplateColumns: "280px 1fr", gap: 12, minHeight: 320 },
  threadList: { border: "1px solid #eee", borderRadius: 8, padding: 8, overflow: "auto" },
  threadBtn: {
    width: "100%",
    textAlign: "left",
    padding: 8,
    marginBottom: 6,
    border: "1px solid #eee",
    borderRadius: 8,
    background: "#fff",
    cursor: "pointer",
    fontSize: 12,
  },
  threadBtnOn: { borderColor: "#E1306C", boxShadow: "0 0 0 2px rgba(225,48,108,.15)" },
  messagePane: { border: "1px solid #eee", borderRadius: 8, padding: 8, overflow: "auto" },
  bubble: {
    marginBottom: 8,
    padding: 8,
    borderRadius: 8,
    background: "#f7f7f9",
    fontSize: 13,
  },
  tabs: { display: "flex", gap: 8, marginBottom: 12 },
  tab: {
    padding: "6px 12px",
    borderRadius: 8,
    border: "1px solid #ddd",
    background: "#fff",
    cursor: "pointer",
    fontSize: 13,
  },
  tabOn: { borderColor: "#E1306C", background: "rgba(225,48,108,.08)", fontWeight: 600 },
  webhookBox: {
    padding: 10,
    border: "1px solid #eee",
    borderRadius: 8,
    marginBottom: 12,
    background: "#fafafa",
  },
  code: { fontSize: 11, background: "#fff", padding: "2px 6px", borderRadius: 4 },
  input: {
    width: "100%",
    padding: 8,
    marginBottom: 8,
    borderRadius: 8,
    border: "1px solid #ddd",
    fontSize: 13,
    boxSizing: "border-box",
  },
  checkRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, marginBottom: 6 },
  rowBetween: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  success: { color: "#0a7", fontSize: 13 },
};
